/* Cognito Hosted UI auth — authorization-code flow WITH PKCE.
   Tokens live in sessionStorage only (per-tab, gone on close); no cookies,
   no localStorage. CONFIG comes from config.js (generated by deploy.sh). */

'use strict';

const Auth = (() => {
  const TOKEN_KEY = 'ktd.tokens';
  const VERIFIER_KEY = 'ktd.pkce_verifier';
  const STATE_KEY = 'ktd.oauth_state';

  /* PKCE verifier/state must survive the cross-origin round-trip to the
     Cognito Hosted UI. Safari (especially iOS) can swap the browsing
     context on that redirect and drop sessionStorage, which strands the
     user on the login screen. These are one-time, short-lived, non-secret
     values, so localStorage is the correct store for them; they are
     removed on first read. TOKENS stay in sessionStorage. */
  const flowStore = {
    set: (k, v) => localStorage.setItem(k, v),
    take: (k) => {              // read-once semantics
      const v = localStorage.getItem(k);
      localStorage.removeItem(k);
      return v;
    },
  };

  const b64url = (bytes) =>
    btoa(String.fromCharCode(...new Uint8Array(bytes)))
      .replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');

  const randomString = () => {
    const bytes = new Uint8Array(32);
    crypto.getRandomValues(bytes);
    return b64url(bytes);
  };

  async function sha256(text) {
    return b64url(await crypto.subtle.digest('SHA-256', new TextEncoder().encode(text)));
  }

  function tokens() {
    try { return JSON.parse(sessionStorage.getItem(TOKEN_KEY)) || null; }
    catch { return null; }
  }

  function isAuthenticated() {
    const t = tokens();
    return !!(t && t.access_token && t.expires_at > Date.now() + 30_000);
  }

  async function login() {
    const verifier = randomString();
    const state = randomString();
    flowStore.set(VERIFIER_KEY, verifier);
    flowStore.set(STATE_KEY, state);
    const challenge = await sha256(verifier);
    const params = new URLSearchParams({
      client_id: CONFIG.clientId,
      response_type: 'code',
      scope: 'openid email',
      redirect_uri: CONFIG.redirectUri,
      state,
      code_challenge: challenge,
      code_challenge_method: 'S256',
    });
    location.assign(`https://${CONFIG.cognitoDomain}/oauth2/authorize?${params}`);
  }

  /* Handle ?code=...&state=... on return from the Hosted UI. */
  async function completeLoginIfCallback() {
    const qs = new URLSearchParams(location.search);
    const code = qs.get('code');
    if (!code) return false;

    const expectedState = flowStore.take(STATE_KEY);
    const verifier = flowStore.take(VERIFIER_KEY);
    // Always scrub the one-time code from the URL/history first, so a
    // failed exchange never retries a consumed code on refresh.
    history.replaceState(null, '', location.pathname);
    if (!expectedState || qs.get('state') !== expectedState) {
      throw new Error('Sign-in session was lost (state mismatch). Please sign in again.');
    }
    if (!verifier) throw new Error('Sign-in session was lost (missing verifier). Please sign in again.');

    const body = new URLSearchParams({
      grant_type: 'authorization_code',
      client_id: CONFIG.clientId,
      code,
      redirect_uri: CONFIG.redirectUri,
      code_verifier: verifier,
    });
    const res = await fetch(`https://${CONFIG.cognitoDomain}/oauth2/token`, {
      method: 'POST',
      headers: { 'content-type': 'application/x-www-form-urlencoded' },
      body,
    });
    if (!res.ok) {
      const detail = await res.json().catch(() => ({}));
      throw new Error(`Sign-in failed (${detail.error || res.status}). Please sign in again.`);
    }
    const t = await res.json();
    t.expires_at = Date.now() + (t.expires_in * 1000);
    sessionStorage.setItem(TOKEN_KEY, JSON.stringify(t));
    return true;
  }

  async function refresh() {
    const t = tokens();
    if (!t || !t.refresh_token) return false;
    const body = new URLSearchParams({
      grant_type: 'refresh_token',
      client_id: CONFIG.clientId,
      refresh_token: t.refresh_token,
    });
    const res = await fetch(`https://${CONFIG.cognitoDomain}/oauth2/token`, {
      method: 'POST',
      headers: { 'content-type': 'application/x-www-form-urlencoded' },
      body,
    });
    if (!res.ok) return false;
    const fresh = await res.json();
    fresh.refresh_token = fresh.refresh_token || t.refresh_token;
    fresh.expires_at = Date.now() + (fresh.expires_in * 1000);
    sessionStorage.setItem(TOKEN_KEY, JSON.stringify(fresh));
    return true;
  }

  function logout() {
    sessionStorage.removeItem(TOKEN_KEY);
    const params = new URLSearchParams({
      client_id: CONFIG.clientId,
      logout_uri: CONFIG.logoutUri,
    });
    location.assign(`https://${CONFIG.cognitoDomain}/logout?${params}`);
  }

  /* Fetch wrapper: attaches the JWT, transparently refreshes once on 401. */
  async function apiFetch(path) {
    if (!isAuthenticated() && !(await refresh())) { logout(); return null; }
    const call = () => fetch(path, {
      headers: { authorization: `Bearer ${tokens().access_token}` },
    });
    let res = await call();
    if (res.status === 401 && await refresh()) res = await call();
    if (res.status === 401) { logout(); return null; }
    if (!res.ok) throw new Error(`API ${res.status}`);
    return res.json();
  }

  /* PUT wrapper for admin writes (policy). Same auth/refresh flow. */
  async function apiPut(path, bodyObj) {
    if (!isAuthenticated() && !(await refresh())) { logout(); return null; }
    const call = () => fetch(path, {
      method: 'PUT',
      headers: {
        authorization: `Bearer ${tokens().access_token}`,
        'content-type': 'application/json',
      },
      body: JSON.stringify(bodyObj),
    });
    let res = await call();
    if (res.status === 401 && await refresh()) res = await call();
    if (!res.ok) {
      const detail = await res.json().catch(() => ({}));
      throw new Error(detail.error || `API ${res.status}`);
    }
    return res.json();
  }

  return { login, logout, completeLoginIfCallback, isAuthenticated, apiFetch, apiPut };
})();
