/* Generated by scripts/deploy.sh — DO NOT edit config.js by hand.
   This example documents the shape; real values come from stack outputs. */
const CONFIG = {
  cognitoDomain: 'REPLACED-BY-DEPLOY.auth.us-east-1.amazoncognito.com',
  clientId: 'REPLACED-BY-DEPLOY',
  redirectUri: 'https://REPLACED-BY-DEPLOY.cloudfront.net/',
  logoutUri: 'https://REPLACED-BY-DEPLOY.cloudfront.net/',
};
